# Generated by Django 6.0.3 on 2026-06-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailOTP',
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.CharField(blank=True, choices=[('pet', 'What was the name of your first pet?'), ('city', 'In what city were you born?'), ('mother', "What is your mother's maiden name?"), ('school', 'What was the name of your first school?'), ('car', 'What was the make of your first car?')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
